# settings lambda — view/edit the system prompts the agent + ingest pipeline
# use. Stores overrides globally (one row per prompt_id) in the kb_cache table
# under pk = "settings#prompts". Defaults are bundled into the lambda from
# lambda/settings/defaults.json (regenerated by scripts/sync_default_prompts.py).
#
# Browser → CloudFront `/settings/*` → HTTP API → this lambda → DDB.

locals {
  settings_root = "${path.module}/../lambda/settings"
}

data "archive_file" "settings" {
  type        = "zip"
  source_dir  = local.settings_root
  output_path = "${path.module}/.build/settings.zip"
}

resource "aws_iam_role" "settings" {
  name               = "${local.fqname}-settings"
  assume_role_policy = data.aws_iam_policy_document.lambda_assume.json
}

resource "aws_iam_role_policy_attachment" "settings_basic" {
  role       = aws_iam_role.settings.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

data "aws_iam_policy_document" "settings_perms" {
  statement {
    sid = "PromptOverridesRW"
    actions = [
      "dynamodb:GetItem",
      "dynamodb:PutItem",
      "dynamodb:DeleteItem",
      "dynamodb:Query",
    ]
    resources = [aws_dynamodb_table.kb_cache.arn]
  }
}

resource "aws_iam_role_policy" "settings" {
  role   = aws_iam_role.settings.id
  policy = data.aws_iam_policy_document.settings_perms.json
}

resource "aws_lambda_function" "settings" {
  function_name    = "${local.fqname}-settings"
  role             = aws_iam_role.settings.arn
  runtime          = "nodejs20.x"
  handler          = "index.handler"
  filename         = data.archive_file.settings.output_path
  source_code_hash = data.archive_file.settings.output_base64sha256
  timeout          = 15
  memory_size      = 256

  tracing_config { mode = "Active" }

  environment {
    variables = {
      KB_CACHE_TABLE       = aws_dynamodb_table.kb_cache.name
      COGNITO_USER_POOL_ID = aws_cognito_user_pool.this.id
      COGNITO_CLIENT_ID    = aws_cognito_user_pool_client.spa.id
      ADMIN_GROUP_NAME     = aws_cognito_user_group.admins.name
    }
  }
}

resource "aws_cloudwatch_log_group" "settings" {
  name              = "/aws/lambda/${aws_lambda_function.settings.function_name}"
  retention_in_days = 14
}

# ─── HTTP API routes /settings/* → settings lambda ──────────────────────
resource "aws_apigatewayv2_integration" "settings" {
  api_id                 = aws_apigatewayv2_api.http.id
  integration_type       = "AWS_PROXY"
  integration_uri        = aws_lambda_function.settings.invoke_arn
  payload_format_version = "2.0"
}

locals {
  settings_routes = [
    "GET /settings/prompts",
    "OPTIONS /settings/prompts",
    "PUT /settings/prompts/{id}",
    "DELETE /settings/prompts/{id}",
    "OPTIONS /settings/prompts/{id}",
  ]
}

resource "aws_apigatewayv2_route" "settings" {
  for_each  = toset(local.settings_routes)
  api_id    = aws_apigatewayv2_api.http.id
  route_key = each.value
  target    = "integrations/${aws_apigatewayv2_integration.settings.id}"
}

resource "aws_lambda_permission" "http_invoke_settings" {
  statement_id  = "AllowHttpInvokeSettings"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.settings.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.http.execution_arn}/*"
}
