#!/usr/bin/env python3
"""Generate a deployable zip release of tl-agentcore.

Builds a clean tree from `git archive HEAD` (tracked files only), strips
operator-specific artifacts + sensitive defaults, replaces them with
placeholder examples, runs a secret-shape scan, and emits a versioned
zip plus a SHA-256 sidecar.

Best practices enforced:

  · `git archive` skips everything in .gitignore (.env, .terraform, .venv,
    node_modules, etc.) so untracked state can never leak.
  · An additional EXCLUDE list removes files that ARE tracked but
    shouldn't ship: the stamped ui/.env.production, the stale
    infra/.build lambda zips, internal review docs.
  · Sensitive defaults baked into source (CloudFront URL, AWS account id,
    fqname prefix) are replaced with `__REPLACE_ME__` placeholders so a
    fresh deployer can `grep -r __REPLACE_ME__` to find every setting.
  · A SECRET-SHAPE SCAN aborts the build if any tracked file contains a
    pattern matching common credential formats (tlk_*, gho_*, AKIA*,
    AROA*, AWS_SECRET_ACCESS_KEY, BEGIN PRIVATE KEY, …). The whitelist
    covers literal documentation examples like `tlk_...`.
  · The script refuses to run on a dirty working tree unless --allow-dirty
    is passed.
  · The output zip is reproducible-ish: file order is sorted; mtimes are
    pinned to the HEAD commit timestamp.

Usage:
  scripts/make_release.py                      # version from git describe
  scripts/make_release.py --version v0.3.0     # explicit version
  scripts/make_release.py --allow-dirty        # skip clean-tree check
  scripts/make_release.py --no-sanitize        # leave operator strings as-is
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import time
import zipfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RELEASE_DIR = ROOT / "release"

# Files that are tracked in git but must NOT ship in a release.
EXCLUDE_PATHS: list[str] = [
    # Operator-specific stamped env. We replace this with a template.
    "ui/.env.production",
    # Internal review notes.
    "docs/comment-replies.md",
    # E2E suite. The whole folder + Playwright config + CI workflows + the
    # bootstrap script all go. Shipping these requires a Cognito test user
    # and a paid AWS+TL pass, neither of which a fresh deployer has.
    "ui/e2e",
    "ui/playwright.config.ts",
    "ui/playwright-report",
    "ui/test-results",
    ".github",
    "scripts/setup_test_fixtures.sh",
    # Whitepaper diagrams (mermaid sources + rendered PNGs + viewer HTML).
    # Only the whitepaper / internal docs reference these, and those are
    # already stripped by the markdown allowlist.
    "docs/diagrams",
    # TypeScript incremental build cache.
    "ui/tsconfig.tsbuildinfo",
    # The entire scripts/ directory. Every script in it is either a
    # CLI ingestion fallback (made redundant by the in-app upload's
    # auto-pipeline: presign_upload → embed_clip_start →
    # embed_clip_finalize → hls_finalize → asset_profile → ks_rollup),
    # a one-shot backfill, an operator-specific seeder, or maintainer
    # tooling (this very script).
    "scripts",
    # Local-only smoke driver + gdino tuning tools.
    "agent/local_run.py",
    "agent/expert-models/gdino/scripts",
    # All-e2e Makefile — every target points at the stripped e2e suite.
    "Makefile",
    # Maintainer-side quality eval harness. Compares entity-reID pipelines
    # against ground-truth labels. Has its own README, dependencies, and
    # AWS-side data (Rekognition collection, shadow S3 Vectors index)
    # that a deployer doesn't need.
    "eval",
    # Claude Code project instructions.
    "CLAUDE.md",
    ".claude",
    # Editor / OS metadata.
    ".vscode",
    ".idea",
]

# Markdown allowlist: every other `*.md` in the tree is removed. The
# deployment guide is the only doc shipped; the whitepaper, scope,
# cost-estimate, and per-folder READMEs are stripped. RELEASE_NOTES.md
# is generated AFTER pruning and is preserved by construction.
MARKDOWN_KEEP: set[str] = {
    "docs/deployment.md",
}

# Glob patterns that are recursively removed from the staging tree
# regardless of whether they were tracked.
EXCLUDE_GLOBS: list[str] = [
    "**/__pycache__",
    "**/.pytest_cache",
    "**/.DS_Store",
    "**/.venv",
    "**/.vite",
    "**/node_modules",
    "**/dist",
    "**/.next",
    "**/.terraform",
    "**/*.tfstate",
    "**/*.tfstate.*",
    "**/*.tfvars",
    "**/*.log",
    "**/storage-state.json",
    "**/.env",
    "**/.env.local",
    "**/.env.test",
    # Stale lambda build artifacts. infra/.build/ accumulates a *.zip per
    # lambda over time. Every one is regenerated by `terraform apply` so
    # none of them need to ship. Wipe the whole directory.
    "infra/.build",
    # Local Cursor / Claude Code project state.
    "**/.claude",
    "**/.cursor",
    # macOS extended attributes.
    "**/._*",
]

# Hard-fail patterns: any match terminates the release with an error.
# A leaked one of these would expose an actual credential.
SECRET_SHAPE_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    ("TwelveLabs API key (tlk_)", re.compile(r"\btlk_[A-Z0-9]{20,}\b")),
    ("GitHub personal token (gho_)", re.compile(r"\bgho_[A-Za-z0-9]{30,}\b")),
    ("GitHub OAuth token (ghp_)", re.compile(r"\bghp_[A-Za-z0-9]{30,}\b")),
    ("AWS access key (AKIA)", re.compile(r"\bAKIA[0-9A-Z]{16,}\b")),
    ("AWS role access key (AROA)", re.compile(r"\bAROA[0-9A-Z]{16,}\b")),
    ("AWS secret access key kv", re.compile(r"aws_secret_access_key\s*=\s*[A-Za-z0-9/+=]{30,}", re.IGNORECASE)),
    ("Anthropic API key (sk-ant-)", re.compile(r"\bsk-ant-[A-Za-z0-9_-]{20,}\b")),
    ("OpenAI API key (sk-)", re.compile(r"\bsk-(proj-)?[A-Za-z0-9]{40,}\b")),
    ("PEM private key", re.compile(r"-----BEGIN (?:RSA |EC )?PRIVATE KEY-----")),
    ("JWT-shaped token", re.compile(r"\beyJ[A-Za-z0-9_-]{12,}\.[A-Za-z0-9_-]{12,}\.[A-Za-z0-9_-]{6,}\b")),
]

# Files where literal operator strings appear ON PURPOSE — this script
# embeds the patterns to find them, so we must NOT rewrite our own table.
# Listed as paths relative to the staging root.
SANITIZE_SKIP: set[str] = {
    "scripts/make_release.py",
}


# Soft-warn patterns: operator-specific values that shouldn't ship as
# defaults but aren't secrets per se. If --sanitize is on (the default)
# they get rewritten in place to a placeholder. Otherwise just warned.
SANITIZE_REPLACEMENTS: list[tuple[str, re.Pattern[str], str]] = [
    ("AWS account id (12-digit)", re.compile(r"\b026090552520\b"), "<ACCOUNT_ID>"),
    ("Deployed CloudFront URL",   re.compile(r"\bd18q1864w6gq7b\.cloudfront\.net\b"), "<FRONTEND_URL>"),
    ("Stack name prefix (fqname)", re.compile(r"\btl-agentcore-1c323e\b"), "<STACK_FQNAME>"),
    ("AgentCore runtime id suffix", re.compile(r"\b1c323e_agent-[A-Za-z0-9]+\b"), "1c323e_agent-<RUNTIME_ID>"),
    ("Cognito user pool id", re.compile(r"\bus-east-1_LQDmyKlEp\b"), "<COGNITO_USER_POOL_ID>"),
    ("Cognito SPA client id", re.compile(r"\b1crao93ilherqgrk1s4vomcmuu\b"), "<COGNITO_CLIENT_ID>"),
    ("HTTP API id", re.compile(r"\bd9fdoup7na\b"), "<HTTP_API_ID>"),
    ("WS API id", re.compile(r"\bx822n3qkvc\b"), "<WS_API_ID>"),
    ("CloudFront distribution id", re.compile(r"\bE14YD89QBQPVN5\b"), "<CLOUDFRONT_DISTRIBUTION_ID>"),
    ("Operator's S3 source bucket", re.compile(r"\blior-test-files\b"), "<SOURCE_BUCKET>"),
]

# Text file extensions worth scanning. Everything else (binaries, fonts,
# images) is passed through without inspection.
TEXT_SUFFIXES = {
    ".py", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs",
    ".json", ".yaml", ".yml", ".toml",
    ".md", ".txt", ".html", ".css", ".sh", ".tf", ".hcl",
    ".env", ".example", ".lock",
}
SCAN_MAX_BYTES = 4 * 1024 * 1024  # skip giant binaries / lockfiles


# Replacement content for ui/.env.production — published as a clearly-
# labeled example so a fresh deployer knows exactly which vars to fill.
ENV_PRODUCTION_EXAMPLE = """\
# Frontend environment for `npm run build`. Each value is stamped into
# the SPA bundle. Fill these in after `terraform apply` — `terraform
# output ui_env` prints the exact key=value pairs you need here.
#
# Rename this file to `.env.production` (Vite picks it up automatically).

VITE_AGENT_RUNTIME_ARN=arn:aws:bedrock-agentcore:us-east-1:<ACCOUNT_ID>:runtime/<RUNTIME_NAME>
VITE_AGENT_RUNTIME_REGION=us-east-1
VITE_AGENT_RUNTIME_QUALIFIER=live
VITE_COGNITO_HOSTED_UI_DOMAIN=https://<COGNITO_DOMAIN>.auth.us-east-1.amazoncognito.com
VITE_COGNITO_CLIENT_ID=<COGNITO_CLIENT_ID>
VITE_FRONTEND_URL=https://<CLOUDFRONT_DOMAIN>
"""


# ─── helpers ────────────────────────────────────────────────────────────────


def run(cmd: list[str], check: bool = True, capture: bool = True) -> str:
    res = subprocess.run(cmd, cwd=ROOT, check=check,
                         text=True, capture_output=capture)
    return (res.stdout or "").strip()


def git_describe_version() -> str:
    try:
        return run(["git", "describe", "--tags", "--always", "--dirty=-dev"])
    except subprocess.CalledProcessError:
        return "v0.0.0-unknown"


def working_tree_clean() -> bool:
    out = run(["git", "status", "--porcelain"])
    return not out


def head_commit_timestamp() -> int:
    return int(run(["git", "log", "-1", "--format=%ct"]))


def staging_path(version: str) -> Path:
    return RELEASE_DIR / f"tl-agentcore-{version}"


def archive_to_staging(stage: Path) -> None:
    """git archive HEAD → tar → extract into staging.
    Only tracked + committed files. Clean and deterministic."""
    stage.mkdir(parents=True, exist_ok=True)
    proc = subprocess.Popen(
        ["git", "archive", "--format=tar", "HEAD"],
        cwd=ROOT, stdout=subprocess.PIPE,
    )
    assert proc.stdout
    with tarfile.open(fileobj=proc.stdout, mode="r|") as tar:
        # data filter is the safe extraction default in 3.12+; older
        # Pythons fall back to fully_trusted.
        try:
            tar.extractall(stage, filter="data")  # type: ignore[arg-type]
        except TypeError:
            tar.extractall(stage)
    if proc.wait() != 0:
        raise RuntimeError("git archive failed")


def worktree_to_staging(stage: Path) -> None:
    """Copy the CURRENT working tree to staging, including uncommitted
    changes, while still honoring `.gitignore`. Uses git's own ls-files
    to enumerate (cached + modified + others-not-ignored) so we mirror
    git's notion of "interesting" files exactly. Used for shipping a
    release from a session of in-progress, not-yet-committed work."""
    stage.mkdir(parents=True, exist_ok=True)
    # -c = committed, -m = modified, -o = untracked, --exclude-standard
    # applies .gitignore + global excludes. Deletions are omitted by
    # default which is what we want here.
    out = run(["git", "ls-files", "-c", "-m", "-o", "--exclude-standard"])
    files = [line for line in out.splitlines() if line.strip()]
    for rel in files:
        src = ROOT / rel
        if not src.is_file():
            continue  # deleted between ls-files and now
        dst = stage / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


def remove_excludes(stage: Path) -> list[str]:
    removed: list[str] = []
    for rel in EXCLUDE_PATHS:
        p = stage / rel
        if p.exists():
            if p.is_dir():
                shutil.rmtree(p)
            else:
                p.unlink()
            removed.append(rel)
    for glob in EXCLUDE_GLOBS:
        for p in stage.rglob(glob.lstrip("**/")):
            try:
                if p.is_dir():
                    shutil.rmtree(p)
                else:
                    p.unlink()
                removed.append(str(p.relative_to(stage)))
            except FileNotFoundError:
                pass
    return removed


def prune_markdown(stage: Path) -> list[str]:
    """Remove every `*.md` file except those in MARKDOWN_KEEP."""
    removed: list[str] = []
    for p in stage.rglob("*.md"):
        if not p.is_file():
            continue
        rel = str(p.relative_to(stage))
        if rel in MARKDOWN_KEEP:
            continue
        p.unlink()
        removed.append(rel)
    return removed


def write_env_template(stage: Path) -> None:
    target = stage / "ui" / ".env.production.example"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(ENV_PRODUCTION_EXAMPLE)


def iter_text_files(stage: Path):
    for p in stage.rglob("*"):
        if not p.is_file():
            continue
        if p.suffix.lower() not in TEXT_SUFFIXES and p.name not in {".env.example", "Dockerfile", "Makefile"}:
            continue
        try:
            if p.stat().st_size > SCAN_MAX_BYTES:
                continue
        except OSError:
            continue
        yield p


def scan_for_secrets(stage: Path) -> list[tuple[str, str, str]]:
    """Return [(rel_path, pattern_name, line)] for every hard-fail hit."""
    hits: list[tuple[str, str, str]] = []
    for p in iter_text_files(stage):
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for name, pat in SECRET_SHAPE_PATTERNS:
            for m in pat.finditer(text):
                # Filter docstring placeholders like `tlk_...`.
                snippet = m.group(0)
                if snippet.endswith("..."):
                    continue
                # Line context for the report.
                start = text.rfind("\n", 0, m.start()) + 1
                end = text.find("\n", m.end())
                line = text[start: end if end != -1 else len(text)]
                hits.append((str(p.relative_to(stage)), name, line.strip()[:160]))
    return hits


def sanitize_operator_strings(stage: Path) -> tuple[dict[str, int], list[str]]:
    """Replace operator-specific defaults in place. Returns (counts_by_label, files_modified)."""
    counts: dict[str, int] = {}
    modified: list[str] = []
    for p in iter_text_files(stage):
        rel = str(p.relative_to(stage))
        if rel in SANITIZE_SKIP:
            continue
        try:
            original = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        new_text = original
        for label, pat, replacement in SANITIZE_REPLACEMENTS:
            new_text, n = pat.subn(replacement, new_text)
            if n:
                counts[label] = counts.get(label, 0) + n
        if new_text != original:
            p.write_text(new_text, encoding="utf-8")
            modified.append(rel)
    return counts, modified


def report_operator_strings(stage: Path) -> dict[str, int]:
    """Just count occurrences without modifying — for --no-sanitize mode."""
    counts: dict[str, int] = {}
    for p in iter_text_files(stage):
        try:
            text = p.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for label, pat, _ in SANITIZE_REPLACEMENTS:
            n = len(pat.findall(text))
            if n:
                counts[label] = counts.get(label, 0) + n
    return counts


def zip_staging(stage: Path, version: str, mtime: int) -> Path:
    out = RELEASE_DIR / f"tl-agentcore-{version}.zip"
    if out.exists():
        out.unlink()
    paths = sorted(p for p in stage.rglob("*") if p.is_file())
    with zipfile.ZipFile(out, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        for p in paths:
            rel = p.relative_to(stage.parent)  # prefix dirname inside zip
            info = zipfile.ZipInfo(str(rel))
            info.date_time = time.gmtime(mtime)[:6]
            info.compress_type = zipfile.ZIP_DEFLATED
            z.writestr(info, p.read_bytes())
    return out


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def write_release_notes(stage: Path, version: str, head_sha: str, mtime: int) -> None:
    iso = datetime.fromtimestamp(mtime, tz=timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    body = f"""# Release {version}

- **Commit**: `{head_sha}`
- **Built**: {iso}

## What's in the box

- `agent/` — Strands agent (Python, arm64 Docker image) for AgentCore Runtime
- `lambda/` — chat, kb_admin, kb_graph, presign_upload, embed_clip_start/finalize,
  asset_profile, ks_rollup, hls_finalize, stitch, settings, users, …
- `infra/` — Terraform stack (AgentCore Runtime, S3 Vectors, Cognito,
  CloudFront, API Gateways)
- `ui/` — React + Vite SPA
- `docs/deployment.md` — operator-facing deployment notes

## Quick start

1. `cd infra && terraform init && terraform apply -var aws_profile=<your-profile>`
2. `cd ../agent && ./build-image.sh` (or `infra/build-agent.sh`) — pushes
   the arm64 image to ECR.
3. `terraform apply -var agent_image_tag=<tag>` to point the runtime at it.
4. Copy `ui/.env.production.example` → `ui/.env.production`, fill in the
   values from `terraform output ui_env`.
5. `cd ui && npm install && npm run build && aws s3 sync dist/ s3://<frontend-bucket>`
6. See `docs/deployment.md` for the full walkthrough.

## What was sanitized out

This zip was built by `scripts/make_release.py`, which strips
operator-specific defaults from source (AWS account id, deployed
CloudFront URL, Cognito ids, AgentCore runtime ARN, stack-name prefix)
and replaces them with `<PLACEHOLDER>` strings. `grep -r '<.*>' .` will
surface every value a fresh deployer needs to fill in. The script also
removes stale lambda zips under `infra/.build/`, the stamped
`ui/.env.production`, and any cached test fixtures.

It runs a hard-fail secret-shape scan before zipping; release fails if
any tlk_ / gho_ / AKIA / sk-ant- / PEM / JWT-shaped string survives.
"""
    (stage / "RELEASE_NOTES.md").write_text(body)


# ─── main ───────────────────────────────────────────────────────────────────


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--version", help="release tag (e.g. v0.3.0). Defaults to `git describe`.")
    ap.add_argument("--allow-dirty", action="store_true",
                    help="skip the clean-tree check. With the default HEAD source, "
                         "uncommitted changes will NOT be in the release.")
    ap.add_argument("--from-worktree", action="store_true",
                    help="ship the current working tree (cached + modified + untracked) "
                         "instead of HEAD. Honors .gitignore. Use this when you want to "
                         "include uncommitted changes — common during a session of "
                         "in-progress work that hasn't been committed yet.")
    ap.add_argument("--no-sanitize", action="store_true",
                    help="don't auto-replace operator-specific defaults; just warn")
    ap.add_argument("--keep-stage", action="store_true",
                    help="leave the unzipped staging directory in place after zipping")
    args = ap.parse_args(argv[1:])

    is_dirty = not working_tree_clean()
    if is_dirty and not args.allow_dirty and not args.from_worktree:
        print("error: working tree is dirty. Options:")
        print("  · commit / stash first (cleanest, deterministic release)")
        print("  · pass --from-worktree to include uncommitted changes")
        print("  · pass --allow-dirty to archive HEAD anyway (uncommitted work WON'T ship)")
        run(["git", "status", "--short"], capture=False)
        return 1

    version = args.version or git_describe_version()
    head_sha = run(["git", "rev-parse", "--short", "HEAD"])
    head_mtime = head_commit_timestamp()
    # Worktree builds use "now" as the mtime so the zip reflects when the
    # release was actually cut, not when HEAD was committed.
    build_mtime = int(time.time()) if args.from_worktree else head_mtime
    source_label = "WORKTREE (cached + modified + untracked)" if args.from_worktree else f"HEAD ({head_sha})"

    print(f"\n▌ tl-agentcore release  {version}")
    print(f"▌ Source:                {source_label}")
    if args.from_worktree and is_dirty:
        print("▌ Including uncommitted changes from this session.")
    elif is_dirty:
        print("▌ ⚠ Working tree is dirty but releasing from HEAD — uncommitted changes are EXCLUDED.")
    print(f"▌ Build time:            {datetime.fromtimestamp(build_mtime, tz=timezone.utc).isoformat()}")

    RELEASE_DIR.mkdir(exist_ok=True)
    stage = staging_path(version)
    if stage.exists():
        shutil.rmtree(stage)

    print("\n[1/6] source → staging")
    if args.from_worktree:
        worktree_to_staging(stage)
    else:
        archive_to_staging(stage)
    n_files = sum(1 for _ in stage.rglob("*") if _.is_file())
    print(f"      {n_files} files")

    print("\n[2/6] removing release-excluded files")
    removed = remove_excludes(stage)
    pruned_md = prune_markdown(stage)
    if pruned_md:
        keep = ", ".join(sorted(MARKDOWN_KEEP))
        print(f"      − {len(pruned_md)} markdown file(s) (kept: {keep})")
    for r in removed[:20]:
        print(f"      − {r}")
    if len(removed) > 20:
        print(f"      − … and {len(removed) - 20} more")

    print("\n[3/6] writing ui/.env.production.example template")
    write_env_template(stage)

    if args.no_sanitize:
        print("\n[4/6] operator-specific strings (sanitization disabled)")
        counts = report_operator_strings(stage)
        for label, n in counts.items():
            print(f"      ! {n}× {label}")
        if not counts:
            print("      (none found)")
    else:
        print("\n[4/6] sanitizing operator-specific strings → <PLACEHOLDERS>")
        counts, modified = sanitize_operator_strings(stage)
        for label, n in counts.items():
            print(f"      · {n}× {label}")
        print(f"      ({len(modified)} files modified)")

    print("\n[5/6] secret-shape scan (hard-fail if any hit)")
    hits = scan_for_secrets(stage)
    if hits:
        print(f"\n      ✘ {len(hits)} secret-shaped string(s) found — refusing to publish.\n")
        for path, name, line in hits[:50]:
            print(f"      ✘ {path}  ::  {name}")
            print(f"          {line}")
        return 2
    print("      ✓ clean")

    write_release_notes(stage, version, head_sha, build_mtime)

    print("\n[6/6] zipping")
    zip_path = zip_staging(stage, version, build_mtime)
    sha = sha256_file(zip_path)
    (zip_path.with_suffix(".zip.sha256")).write_text(f"{sha}  {zip_path.name}\n")

    n_zipped = sum(1 for _ in stage.rglob("*") if _.is_file())
    size_mb = zip_path.stat().st_size / (1024 * 1024)

    print(f"\n  zip:    {zip_path.relative_to(ROOT)}")
    print(f"  files:  {n_zipped}")
    print(f"  size:   {size_mb:.2f} MB")
    print(f"  sha256: {sha}")

    if not args.keep_stage:
        shutil.rmtree(stage)
    else:
        print(f"  stage:  {stage.relative_to(ROOT)} (kept)")

    print("\n✓ release ready")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
